/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_application_EmbeddedAndroidThings_Gpio */

#ifndef _Included_com_example_application_EmbeddedAndroidThings_Gpio
#define _Included_com_example_application_EmbeddedAndroidThings_Gpio
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_application_EmbeddedAndroidThings_Gpio_CHIP_A
#define com_example_application_EmbeddedAndroidThings_Gpio_CHIP_A 0L
#undef com_example_application_EmbeddedAndroidThings_Gpio_CHIP_B
#define com_example_application_EmbeddedAndroidThings_Gpio_CHIP_B 1L
#undef com_example_application_EmbeddedAndroidThings_Gpio_LINE_0
#define com_example_application_EmbeddedAndroidThings_Gpio_LINE_0 0L
#undef com_example_application_EmbeddedAndroidThings_Gpio_LINE_1
#define com_example_application_EmbeddedAndroidThings_Gpio_LINE_1 1L
#undef com_example_application_EmbeddedAndroidThings_Gpio_STATE_INVALID
#define com_example_application_EmbeddedAndroidThings_Gpio_STATE_INVALID -2L
#undef com_example_application_EmbeddedAndroidThings_Gpio_STATE_NOT_USED
#define com_example_application_EmbeddedAndroidThings_Gpio_STATE_NOT_USED -1L
#undef com_example_application_EmbeddedAndroidThings_Gpio_STATE_LOW
#define com_example_application_EmbeddedAndroidThings_Gpio_STATE_LOW 0L
#undef com_example_application_EmbeddedAndroidThings_Gpio_STATE_HIGH
#define com_example_application_EmbeddedAndroidThings_Gpio_STATE_HIGH 1L
#undef com_example_application_EmbeddedAndroidThings_Gpio_DIRECTION_OUT
#define com_example_application_EmbeddedAndroidThings_Gpio_DIRECTION_OUT 0L
#undef com_example_application_EmbeddedAndroidThings_Gpio_DIRECTION_IN
#define com_example_application_EmbeddedAndroidThings_Gpio_DIRECTION_IN 1L
/*
 * Class:     com_example_application_EmbeddedAndroidThings_Gpio
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Gpio_close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Gpio
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_application_EmbeddedAndroidThings_Gpio_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Gpio
 * Method:    setDirection
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Gpio_setDirection
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Gpio
 * Method:    setState
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Gpio_setState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Gpio
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_application_EmbeddedAndroidThings_Gpio_getState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
