/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_application_EmbeddedAndroidThings_I2c */

#ifndef _Included_com_example_application_EmbeddedAndroidThings_I2c
#define _Included_com_example_application_EmbeddedAndroidThings_I2c
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_application_EmbeddedAndroidThings_I2c_INDEX_0
#define com_example_application_EmbeddedAndroidThings_I2c_INDEX_0 0L
#undef com_example_application_EmbeddedAndroidThings_I2c_INDEX_1
#define com_example_application_EmbeddedAndroidThings_I2c_INDEX_1 1L
/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    readRegByte
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_readRegByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    readRegWord
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_readRegWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    readRegBuffer
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_readRegBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    write
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    writeRegByte
 * Signature: (IB)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_writeRegByte
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    writeRegWord
 * Signature: (IS)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_writeRegWord
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_I2c
 * Method:    writeRegBuffer
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_I2c_writeRegBuffer
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
