/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_application_EmbeddedAndroidThings_Uart */

#ifndef _Included_com_example_application_EmbeddedAndroidThings_Uart
#define _Included_com_example_application_EmbeddedAndroidThings_Uart
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_application_EmbeddedAndroidThings_Uart_INDEX_0
#define com_example_application_EmbeddedAndroidThings_Uart_INDEX_0 0L
#undef com_example_application_EmbeddedAndroidThings_Uart_INDEX_1
#define com_example_application_EmbeddedAndroidThings_Uart_INDEX_1 1L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_1200
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_1200 1200L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_2400
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_2400 2400L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_4800
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_4800 4800L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_9600
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_9600 9600L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_19200
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_19200 19200L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_38400
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_38400 38400L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_57600
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_57600 57600L
#undef com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_115200
#define com_example_application_EmbeddedAndroidThings_Uart_BAUDRATE_115200 115200L
#undef com_example_application_EmbeddedAndroidThings_Uart_FLUSH_IN
#define com_example_application_EmbeddedAndroidThings_Uart_FLUSH_IN 0L
#undef com_example_application_EmbeddedAndroidThings_Uart_FLUSH_OUT
#define com_example_application_EmbeddedAndroidThings_Uart_FLUSH_OUT 1L
#undef com_example_application_EmbeddedAndroidThings_Uart_FLUSH_IN_OUT
#define com_example_application_EmbeddedAndroidThings_Uart_FLUSH_IN_OUT 2L
/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    setBaudrate
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_setBaudrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    isDataAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_isDataAvailable
  (JNIEnv *, jobject);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    write
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_application_EmbeddedAndroidThings_Uart
 * Method:    flush
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_application_EmbeddedAndroidThings_Uart_flush
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
